/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package uia.proyectofinal.View;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import uia.proyectofinal.Conecciones.MySQLDB;
import uia.proyectofinal.Data.IS12DAO;
import uia.proyectofinal.Domain.Proyecto;

/**
 *
 * @author Bryan
 */
public class InternalProyecto extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalProyecto
     */
    public InternalProyecto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNP = new javax.swing.JTextField();
        btnProyectoAñadir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Mantenimiento de Proyecto");
        setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setText("Codigo del Proyecto :");

        jLabel2.setText("Nombre del Proyecto:");

        btnProyectoAñadir.setText("Asignar Proyecto ");
        btnProyectoAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProyectoAñadirActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Proyecto");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar Proyecto");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCP)
                            .addComponent(txtNP, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProyectoAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProyectoAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProyectoAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProyectoAñadirActionPerformed
       try {
        
        MySQLDB mysql = new MySQLDB();
       IS12DAO is12 = new IS12DAO();
        String sql = "select *from proyecto.proyectos";
        Proyecto proyecto = new Proyecto();
        proyecto.setCodigo(txtCP.getText());
        proyecto.setNombre(txtNP.getText());
       ResultSet res = mysql.executeQuery(sql);
       
       
           
            
            
            if(res.next()){
                JOptionPane.showMessageDialog(this,"Este proyecto ya fue ingresado");
            
            }else {
                is12.addProyecto(proyecto);
            JOptionPane.showMessageDialog(this,"Su proyecto se ingreso correctamente ");
            }
          
            res.close();
        } catch (SQLException ex) {
            Logger.getLogger(InternalProyecto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnProyectoAñadirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
     try {
        MySQLDB mysql = new MySQLDB();
       IS12DAO is12 = new IS12DAO();
        String sql = "select *from proyecto.proyectos";
        Proyecto proyecto = new Proyecto();
        proyecto.setCodigo(txtCP.getText());
        proyecto.setNombre(txtNP.getText());
    
            ResultSet res = mysql.executeQuery(sql);
            if(res.next()){
                is12.deleteProyecto(proyecto);
                JOptionPane.showMessageDialog(this,"Su proyecto fue eliminado con exito");
            
            }else {
                
            JOptionPane.showMessageDialog(this,"Este proyecto no existe en la DB");
            }
            res.close();
        } catch (SQLException ex) {
            Logger.getLogger(InternalProyecto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
         try {
        MySQLDB mysql = new MySQLDB();
       IS12DAO is12 = new IS12DAO();
        String sql = "select *from proyecto.proyectos";
        Proyecto proyecto = new Proyecto();
        proyecto.setCodigo(txtCP.getText());
        proyecto.setNombre(txtNP.getText());
    
            ResultSet res = mysql.executeQuery(sql);
            if(res.next()){
                is12.updateProyecto(proyecto);
                JOptionPane.showMessageDialog(this,"Su proyecto fue modificado con exito");
            
            }else {
                
            JOptionPane.showMessageDialog(this,"Este proyecto no existe en la DB");
            }
            res.close();
        } catch (SQLException ex) {
            Logger.getLogger(InternalProyecto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnProyectoAñadir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtCP;
    private javax.swing.JTextField txtNP;
    // End of variables declaration//GEN-END:variables
}
